module.exports.data = [
  {
    name: "MTR (Mavalli Tiffin Room)",
    description: "One of Bengaluru's most iconic eateries since 1924. Famous for crispy masala dosas, soft idlis, and authentic filter coffee. Strict kitchen protocols maintained.",
    location: "11, Lalbagh Rd, Mavalli, Bengaluru",
    city: "Bengaluru",
    category: "Restaurant",
    hygieneScore: 94,
    violations: [],
    lastInspected: new Date("2025-11-10"),
    image: { url: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=800&q=80", filename: "mtr" },
    geometry: { type: "Point", coordinates: [77.5946, 12.9519] },
  },
  {
    name: "Vidyarthi Bhavan",
    description: "Legendary breakfast spot in Gandhi Bazaar serving crispy, ghee-soaked dosas since 1943. Clean kitchen, trained staff, and consistent quality.",
    location: "32, Gandhi Bazaar Main Rd, Basavanagudi, Bengaluru",
    city: "Bengaluru",
    category: "Restaurant",
    hygieneScore: 91,
    violations: [],
    lastInspected: new Date("2025-10-25"),
    image: { url: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=800&q=80", filename: "vidyarthi" },
    geometry: { type: "Point", coordinates: [77.5757, 12.9394] },
  },
  {
    name: "Koshy's Parade Cafe",
    description: "A beloved Bengaluru institution since 1940. Serves Continental and Indian cuisine in a warm colonial setting with excellent hygiene standards.",
    location: "39, St Marks Rd, Shivaji Nagar, Bengaluru",
    city: "Bengaluru",
    category: "Cafe",
    hygieneScore: 88,
    violations: [],
    lastInspected: new Date("2025-11-05"),
    image: { url: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800&q=80", filename: "koshys" },
    geometry: { type: "Point", coordinates: [77.6022, 12.9756] },
  },
  {
    name: "Brahmin's Coffee Bar",
    description: "Tiny heritage eatery at Basavanagudi known for incredible idli-vada with sambar and chutney. Simple, clean setup with great hygiene practices.",
    location: "Near DVG Rd, Basavanagudi, Bengaluru",
    city: "Bengaluru",
    category: "Restaurant",
    hygieneScore: 83,
    violations: ["Handwash station needs restocking"],
    lastInspected: new Date("2025-10-30"),
    image: { url: "https://images.unsplash.com/photo-1630383249896-424e482df921?w=800&q=80", filename: "brahmins" },
    geometry: { type: "Point", coordinates: [77.5713, 12.9420] },
  },
  {
    name: "Truffles Indiranagar",
    description: "Popular burger and steak joint in Indiranagar. Known for thick burgers and loaded fries. Well-maintained modern kitchen.",
    location: "4, 100 Feet Rd, Indiranagar, Bengaluru",
    city: "Bengaluru",
    category: "Restaurant",
    hygieneScore: 79,
    violations: ["Minor oil spill near fryer station"],
    lastInspected: new Date("2025-10-15"),
    image: { url: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&q=80", filename: "truffles" },
    geometry: { type: "Point", coordinates: [77.6412, 12.9784] },
  },
  {
    name: "Meghana Foods Koramangala",
    description: "Famous for Andhra-style Biryanis cooked in traditional dum style. Large restaurant serving hundreds daily with consistent food safety practices.",
    location: "74, 1st Cross Rd, Koramangala, Bengaluru",
    city: "Bengaluru",
    category: "Restaurant",
    hygieneScore: 76,
    violations: ["Refrigeration unit running above optimal temperature"],
    lastInspected: new Date("2025-11-01"),
    image: { url: "https://images.unsplash.com/photo-1563379926898-05f4575a45d8?w=800&q=80", filename: "meghana" },
    geometry: { type: "Point", coordinates: [77.6245, 12.9299] },
  },
  {
    name: "Empire Restaurant MG Road",
    description: "One of Bengaluru's most popular chicken spots. Known for the signature pepper chicken and Chicken 65. High volume restaurant with average hygiene score.",
    location: "Church St, Shivaji Nagar, Bengaluru",
    city: "Bengaluru",
    category: "Restaurant",
    hygieneScore: 65,
    violations: ["Food storage containers not fully sealed", "Staff not wearing gloves consistently"],
    lastInspected: new Date("2025-09-20"),
    image: { url: "https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?w=800&q=80", filename: "empire" },
    geometry: { type: "Point", coordinates: [77.6067, 12.9765] },
  },
  {
    name: "VV Puram Food Street",
    description: "Bustling street food strip in Basavanagudi with dozens of vendors selling churmuri, chaat, masala corn, and local sweets. Popular evening destination.",
    location: "VV Puram, Basavanagudi, Bengaluru",
    city: "Bengaluru",
    category: "Street Food",
    hygieneScore: 52,
    violations: ["Open food storage without cover", "Waste not disposed of properly", "No handwash facility for vendors"],
    lastInspected: new Date("2025-10-05"),
    image: { url: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=800&q=80", filename: "vv_puram" },
    geometry: { type: "Point", coordinates: [77.5720, 12.9434] },
  },
  {
    name: "CTR (Central Tiffin Room)",
    description: "Legendary benne (butter) dosa destination in Malleshwaram since 1920. Draws huge crowds every morning for its crispy, golden dosas.",
    location: "7th Cross, Margosa Rd, Malleshwaram, Bengaluru",
    city: "Bengaluru",
    category: "Restaurant",
    hygieneScore: 80,
    violations: ["Queue management leads to crowding near food prep area"],
    lastInspected: new Date("2025-11-08"),
    image: { url: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=800&q=80", filename: "ctr" },
    geometry: { type: "Point", coordinates: [77.5713, 13.0035] },
  },
  {
    name: "Udupi Krishna Bhavan",
    description: "Pure vegetarian Udupi cuisine restaurant in Jayanagar. Offers a wide variety of South Indian thalis, snacks, and fresh juices.",
    location: "4th Block, Jayanagar, Bengaluru",
    city: "Bengaluru",
    category: "Restaurant",
    hygieneScore: 86,
    violations: [],
    lastInspected: new Date("2025-10-28"),
    image: { url: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800&q=80", filename: "udupi_krishna" },
    geometry: { type: "Point", coordinates: [77.5830, 12.9250] },
  },
  {
    name: "Third Wave Coffee Roasters",
    description: "Specialty coffee cafe with multiple Bengaluru outlets. Known for artisanal pour-overs, cold brews, and a clean minimalist ambiance.",
    location: "Lavelle Rd, Ashok Nagar, Bengaluru",
    city: "Bengaluru",
    category: "Cafe",
    hygieneScore: 92,
    violations: [],
    lastInspected: new Date("2025-11-12"),
    image: { url: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800&q=80", filename: "third_wave" },
    geometry: { type: "Point", coordinates: [77.5980, 12.9724] },
  },
  {
    name: "Shivaji Military Hotel",
    description: "No-frills military hotel famous for mutton chops, liver fry, and strong tea. A Bengaluru institution for non-vegetarian South Indian food.",
    location: "Crescent Rd, Sampangi Rama Nagar, Bengaluru",
    city: "Bengaluru",
    category: "Dhaba",
    hygieneScore: 61,
    violations: ["Old grease build-up on cooking equipment", "Inadequate ventilation in kitchen"],
    lastInspected: new Date("2025-09-15"),
    image: { url: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80", filename: "shivaji_hotel" },
    geometry: { type: "Point", coordinates: [77.5920, 12.9880] },
  },
  {
    name: "McDonald's Whitefield",
    description: "Standard McDonald's outlet in Whitefield tech corridor. Follows corporate food safety guidelines with regular third-party audits.",
    location: "ITPL Main Rd, Whitefield, Bengaluru",
    city: "Bengaluru",
    category: "Fast Food",
    hygieneScore: 90,
    violations: [],
    lastInspected: new Date("2025-11-03"),
    image: { url: "https://images.unsplash.com/photo-1619881590738-a111d176d906?w=800&q=80", filename: "mcdonalds" },
    geometry: { type: "Point", coordinates: [77.7480, 12.9698] },
  },
  {
    name: "Mavalli Tiffin (Anna Bhavan)",
    description: "Neighborhood South Indian tiffin joint in BTM Layout. Serves quick, affordable meals. Under scrutiny for inconsistent hygiene.",
    location: "2nd Stage, BTM Layout, Bengaluru",
    city: "Bengaluru",
    category: "Restaurant",
    hygieneScore: 47,
    violations: ["Stagnant water near kitchen entrance", "Food not covered during storage", "Expired condiments found"],
    lastInspected: new Date("2025-09-08"),
    image: { url: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=800&q=80", filename: "anna_bhavan" },
    geometry: { type: "Point", coordinates: [77.6101, 12.9121] },
  },
  {
    name: "Samarkand Restaurant",
    description: "Upscale Central Asian and Mughlai cuisine restaurant near MG Road. Spacious dining, live cooking stations, and strong hygiene protocols.",
    location: "UB City Mall, Vittal Mallya Rd, Bengaluru",
    city: "Bengaluru",
    category: "Restaurant",
    hygieneScore: 96,
    violations: [],
    lastInspected: new Date("2025-11-14"),
    image: { url: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80", filename: "samarkand" },
    geometry: { type: "Point", coordinates: [77.5970, 12.9721] },
  },
  {
    name: "Darshini HSR Layout",
    description: "Classic Bengaluru standing-eating (darshini) style restaurant. Quick service, reasonable prices, and decent hygiene for a fast-paced eatery.",
    location: "27th Main, HSR Layout, Bengaluru",
    city: "Bengaluru",
    category: "Restaurant",
    hygieneScore: 68,
    violations: ["Tables not wiped between customers", "Staff handling cash and food simultaneously"],
    lastInspected: new Date("2025-10-10"),
    image: { url: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800&q=80", filename: "darshini_hsr" },
    geometry: { type: "Point", coordinates: [77.6384, 12.9116] },
  },
  {
    name: "Karavalli (Gateway Hotel)",
    description: "Award-winning coastal Karnataka and Goa cuisine restaurant inside Gateway Hotel. Impeccable hygiene, chef-curated menu, and premium ingredients.",
    location: "66, Residency Rd, Shivaji Nagar, Bengaluru",
    city: "Bengaluru",
    category: "Hotel",
    hygieneScore: 98,
    violations: [],
    lastInspected: new Date("2025-11-15"),
    image: { url: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80", filename: "karavalli" },
    geometry: { type: "Point", coordinates: [77.6044, 12.9742] },
  },
  {
    name: "New Tharagupet Fish Market Stalls",
    description: "Raw fish and seafood market in Tharagupet. Multiple small vendors with varying hygiene levels. High-risk zone for contamination.",
    location: "Tharagupet, Bengaluru",
    city: "Bengaluru",
    category: "Street Food",
    hygieneScore: 31,
    violations: [
      "Fish stored without ice or refrigeration",
      "Waste water pooling around stalls",
      "No handwash facility",
      "Flies present near food",
      "No valid FSSAI license displayed",
    ],
    lastInspected: new Date("2025-08-22"),
    image: { url: "https://images.unsplash.com/photo-1534482421-64566f976cfa?w=800&q=80", filename: "fish_market" },
    geometry: { type: "Point", coordinates: [77.5804, 12.9780] },
  },
  {
    name: "Nagarjuna Restaurant",
    description: "Well-established Andhra-style restaurant famous for its spicy curries and meals. Serves large crowds with consistent recipes.",
    location: "44/1, Residency Rd, Shivaji Nagar, Bengaluru",
    city: "Bengaluru",
    category: "Restaurant",
    hygieneScore: 73,
    violations: ["Kitchen floor slippery — needs non-slip coating"],
    lastInspected: new Date("2025-10-18"),
    image: { url: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800&q=80", filename: "nagarjuna" },
    geometry: { type: "Point", coordinates: [77.6039, 12.9738] },
  },
  {
    name: "Eat Street Banashankari",
    description: "Open-air food court with multiple vendors offering Pan-Indian street food. Evening destination, but sanitation standards need improvement.",
    location: "Banashankari 2nd Stage, Bengaluru",
    city: "Bengaluru",
    category: "Street Food",
    hygieneScore: 44,
    violations: [
      "Shared utensils not sanitized between customers",
      "No dustbins near seating area",
      "Uncovered food at several stalls",
    ],
    lastInspected: new Date("2025-09-28"),
    image: { url: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=800&q=80", filename: "eat_street" },
    geometry: { type: "Point", coordinates: [77.5550, 12.9250] },
  },
];